os:
- linux
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2
install:
- curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/d1db86e02ec31e93c623d4632f8b229c8a8c1793/swiftenv-install.sh | bash
script:
- . ~/.swiftenv/init
- swift build
