os:
- linux
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2
install:
- wget https://github.com/libuv/libuv/archive/v1.7.5.zip -O /tmp/libuv.zip
- unzip /tmp/libuv.zip
- pushd libuv-1.7.5
- sh autogen.sh && ./configure --prefix=/usr && sudo make install
- popd
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
- make caramel
